name: Java CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Start Xvfb
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Install crx tool
        run: npm install -g crx

      - name: Pack extension to crx
        run: crx pack dist -o chrome-extension.crx
        
      - name: Build with Maven
        env:
          DISPLAY: ":99.0"
        run: mvn -B clean verify --file pom.xml
