name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Start Xvfb
        run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &  
        
      - name: Build with Maven
        env:
          DISPLAY: ":99.0"
        run: mvn -B clean verify --file pom.xml
